{
 "title": "Themis benchmark",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Replica 0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "high_mark{job=\"themis-replica-0\"}",
     "legendFormat": "high_mark"
    },
    {
     "expr": "low_mark{job=\"themis-replica-0\"}",
     "legendFormat": "low_mark"
    },
    {
     "expr": "next_sequence{job=\"themis-replica-0\"}",
     "legendFormat": "next_sequence_number"
    },
    {
     "expr": "last_commit{job=\"themis-replica-0\"}",
     "legendFormat": "last_commit"
    }
   ]
  },
  {
   "title": "Replica 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "high_mark{job=\"themis-replica-1\"}",
     "legendFormat": "high_mark"
    },
    {
     "expr": "low_mark{job=\"themis-replica-1\"}",
     "legendFormat": "low_mark"
    },
    {
     "expr": "next_sequence{job=\"themis-replica-1\"}",
     "legendFormat": "next_sequence_number"
    },
    {
     "expr": "last_commit{job=\"themis-replica-1\"}",
     "legendFormat": "last_commit"
    }
   ]
  },
  {
   "title": "Replica 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "high_mark{job=\"themis-replica-2\"}",
     "legendFormat": "high_mark"
    },
    {
     "expr": "low_mark{job=\"themis-replica-2\"}",
     "legendFormat": "low_mark"
    },
    {
     "expr": "next_sequence{job=\"themis-replica-2\"}",
     "legendFormat": "next_sequence_number"
    },
    {
     "expr": "last_commit{job=\"themis-replica-2\"}",
     "legendFormat": "last_commit"
    }
   ]
  },
  {
   "title": "Replica 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "high_mark{job=\"themis-replica-3\"}",
     "legendFormat": "high_mark"
    },
    {
     "expr": "low_mark{job=\"themis-replica-3\"}",
     "legendFormat": "low_mark"
    },
    {
     "expr": "next_sequence{job=\"themis-replica-3\"}",
     "legendFormat": "next_sequence_number"
    },
    {
     "expr": "last_commit{job=\"themis-replica-3\"}",
     "legendFormat": "last_commit"
    }
   ]
  },
  {
   "title": "Request Execution Times - 0",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_execution_times_bucket{job=\"themis-replica-0\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Execution Times - 1",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_execution_times_bucket{job=\"themis-replica-1\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Execution Times - 2",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_execution_times_bucket{job=\"themis-replica-2\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Execution Times - 3",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_execution_times_bucket{job=\"themis-replica-3\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg Execution Time - 0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "request_execution_times_sum{job=\"themis-replica-0\"}/request_execution_times_count{job=\"themis-replica-0\"}",
     "legendFormat": "avg execution time"
    }
   ]
  },
  {
   "title": "Avg Execution Time - 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "request_execution_times_sum{job=\"themis-replica-1\"}/request_execution_times_count{job=\"themis-replica-1\"}",
     "legendFormat": "avg execution time"
    }
   ]
  },
  {
   "title": "Avg Execution Time - 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "request_execution_times_sum{job=\"themis-replica-2\"}/request_execution_times_count{job=\"themis-replica-2\"}",
     "legendFormat": "avg execution time"
    }
   ]
  },
  {
   "title": "Avg Execution Time - 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "request_execution_times_sum{job=\"themis-replica-3\"}/request_execution_times_count{job=\"themis-replica-3\"}",
     "legendFormat": "avg execution time"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "view_number", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Primary",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "is_primary", "legendFormat": "{{job}}" }
   ]
  }
 ]
}